# Generated by Django 3.2.7 on 2021-10-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidphotos',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='principal.aid'),
        ),
    ]
