# Generated by Django 3.2.7 on 2021-10-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
