# Generated by Django 3.2.7 on 2021-10-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_aidphotos_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myaid', to=settings.AUTH_USER_MODEL),
        ),
    ]
