# Generated by Django 3.2.7 on 2021-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_aid_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='state',
            field=models.CharField(choices=[('A', 'Aberto'), ('C', 'Congelado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
