# Generated by Django 3.2.7 on 2021-09-16 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210916_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='socorro',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Necessidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('socorro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.socorro')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socorro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.socorro')),
            ],
        ),
        migrations.CreateModel(
            name='Contribuidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socorro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.socorro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuario')),
            ],
        ),
    ]
