# Generated by Django 3.2.7 on 2021-09-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210916_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='socorro',
        ),
        migrations.RemoveField(
            model_name='necessidades',
            name='socorro',
        ),
        migrations.RemoveField(
            model_name='socorro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='whatsapp',
        ),
        migrations.DeleteModel(
            name='Contribuidores',
        ),
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.DeleteModel(
            name='Necessidades',
        ),
        migrations.DeleteModel(
            name='Socorro',
        ),
    ]
