# Generated by Django 3.2.7 on 2021-10-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_aid_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aid',
            name='contributors',
        ),
    ]
