# Generated by Django 3.2.7 on 2021-09-17 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210917_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSocorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default=0, max_length=8, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=0, max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='a@a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Socorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_conclusao', models.DateTimeField(blank=True)),
                ('estado', models.CharField(choices=[('A', 'Aberto'), ('C', 'Congelado'), ('F', 'Finalizado')], default='A', max_length=1)),
                ('contribuidores', models.ManyToManyField(related_name='contribuidores', to='principal.Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tiposocorro')),
            ],
        ),
        migrations.CreateModel(
            name='Necessidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('NF', 'Não Finalizado'), ('F', 'Finalizado')], default='NF', max_length=2)),
                ('socorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.socorro')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(default='', upload_to='socorros/')),
                ('descricao', models.TextField(blank=True)),
                ('socorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.socorro')),
            ],
        ),
    ]
