# Generated by Django 3.2.8 on 2021-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_aid_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='users/profile_empty.jpg', upload_to='users/'),
        ),
    ]
