# Generated by Django 3.2.7 on 2021-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20211009_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.AlterField(
            model_name='aid',
            name='title',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='users/empty-img-profile.jpg', upload_to='users/'),
        ),
    ]
