# Generated by Django 3.2.8 on 2021-10-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_aid_author'),
        ('principal', '0005_auto_20210929_1615'),
    ]

    operations = [
    ]
