# Generated by Django 3.2.7 on 2021-10-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20211009_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='users/empty-img-profile.jpg', upload_to='users/'),
        ),
        migrations.AddField(
            model_name='aid',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_hits', to='principal.IpModel'),
        ),
    ]
