# Generated by Django 3.2.7 on 2021-10-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20211012_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_hits', to='principal.IpModel'),
        ),
    ]
