# Generated by Django 3.2.7 on 2021-10-13 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_aid_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
